/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ERSpecialistDoctorTeamRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.PatientAttributes.ERVisit;
import Business.PatientAttributes.VitalSigns;
import Business.UserAccount.UserAccount;
import static Business.Utils.Methods.getLastERVisit;
import static Business.Utils.Methods.vitalSignsStatusChecker;
import Business.WorkQueue.RequestERCoordinatorERSpecialist;
import Business.WorkQueue.RequestPatientAmbulance;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mohit
 */
public class ERSpecialistOperationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private RequestERCoordinatorERSpecialist request3;
    private ERSpecialistDoctorTeamWorkAreaJPanel ersdtwajp;
    private ERVisit erVisit;

    /**
     * Creates new form ERSpecialistOperationJPanel
     */
    public ERSpecialistOperationJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, RequestERCoordinatorERSpecialist request3, ERSpecialistDoctorTeamWorkAreaJPanel ersdtwajp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.request3 = request3;
        this.ersdtwajp = ersdtwajp;
        this.erVisit = getLastERVisit(request3);
        patientNameTxtField.setText(request3.getPatient().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        operatePatientBtn = new javax.swing.JButton();
        patientNameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        releasePatientBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedBackTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("ER Specialist Operation ");

        operatePatientBtn.setText("Operate Patient");
        operatePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatePatientBtnActionPerformed(evt);
            }
        });

        patientNameTxtField.setEditable(false);

        jLabel2.setText("Patient");

        releasePatientBtn.setText("Release Patient");
        releasePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releasePatientBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Feedback");

        feedBackTextArea.setColumns(20);
        feedBackTextArea.setRows(5);
        jScrollPane1.setViewportView(feedBackTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(operatePatientBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(patientNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(backBtn)
                        .addGap(67, 67, 67)
                        .addComponent(releasePatientBtn)))
                .addGap(297, 297, 297))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(58, 58, 58)
                .addComponent(operatePatientBtn)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(releasePatientBtn)
                    .addComponent(backBtn))
                .addGap(242, 242, 242))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ersdtwajp.populateTable();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void operatePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatePatientBtnActionPerformed
        // TODO add your handling code here:
        //attribite im ervisit;
        //change status of request to patient operated
        request3.setStatus("Patient is being operated");
        WorkRequest lastRequest = null;
        for (WorkRequest request : request3.getPatient().getUserAccount().getWorkQueue().getWorkRequestList()) {
            if (request instanceof RequestPatientAmbulance) {
                lastRequest = request;
            }
        }
        if(lastRequest!= null){
                lastRequest.setStatus("Patient is being operated");
            }
        int size = request3.getPatient().getErVisitHistory().getErVisitHistory().size();
        ERVisit erVisit = request3.getPatient().getErVisitHistory().getErVisitHistory().get(size - 1);
        erVisit.setIsOperatedBySpecialistTeam(true);
        erVisit.setOperatedBy(request3.getReceiver().getEmployee());
        JOptionPane.showMessageDialog(null, "Patient is being operated");
    }//GEN-LAST:event_operatePatientBtnActionPerformed

    private void releasePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releasePatientBtnActionPerformed
        // TODO add your handling code here:
        //change status if request to patient released
        if (feedBackTextArea.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Leave a Feedback");
            return;
        } else {
            request3.setStatus("Patient is operated and Released");
            WorkRequest lastRequest = null;
            for (WorkRequest request : request3.getPatient().getUserAccount().getWorkQueue().getWorkRequestList()) {
                if (request instanceof RequestPatientAmbulance) {
                    lastRequest = request;
                }
            }
            if(lastRequest!= null){
                lastRequest.setStatus("Patient is operated and Released");
            }
            int size = request3.getPatient().getErVisitHistory().getErVisitHistory().size();
            ERVisit erVisit = request3.getPatient().getErVisitHistory().getErVisitHistory().get(size - 1);
            erVisit.setERDoctorFeedback(feedBackTextArea.getText());
            JOptionPane.showMessageDialog(null, "Patient is Operated");
            VitalSigns vitalSigns = request3.getPatient().getVitalSignsHistory().addVitalSigns();
            vitalSigns.setRespiratoryRate(20);
            vitalSigns.setHeartRate(72);
            vitalSigns.setSystolicBloodPressure(90);
            vitalSigns.setWeightInKg(80);
            vitalSigns.setEcg(48);
            vitalSigns.setTimeStamp(new Date());
            vitalSigns.setStatus(vitalSignsStatusChecker(48));
        }


    }//GEN-LAST:event_releasePatientBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea feedBackTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton operatePatientBtn;
    private javax.swing.JTextField patientNameTxtField;
    private javax.swing.JButton releasePatientBtn;
    // End of variables declaration//GEN-END:variables

}
