/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PDCNurseRole;

import Business.Employee.Employee;
import Business.Employee.PrimaryDoctor;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PDCPrimaryDoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.Utils.Methods;
import Business.WorkQueue.RequestPDCNursePDCPrimaryDoctor;
import Business.WorkQueue.RequestPDCReceptionistPDCNurse;
import Business.WorkQueue.RequestPatientPDCReceptionist;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mohit
 */
public class PDCNurseProcessJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private RequestPDCReceptionistPDCNurse request6;
    private UserAccount userAccount;
    private Enterprise enterprise;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public PDCNurseProcessJPanel(JPanel userProcessContainer, RequestPDCReceptionistPDCNurse request6, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request6 = request6;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendToDoctorBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        monitorVitalSignsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendToDoctorBtn.setText("Send To Doctor");
        sendToDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToDoctorBtnActionPerformed(evt);
            }
        });
        add(sendToDoctorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 110, -1));

        jLabel1.setText("Check for Vital Signs of Patient Here and Send Patient to the Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 30, -1, -1));

        monitorVitalSignsBtn.setText("Monitor Vital Signs of Patient");
        monitorVitalSignsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorVitalSignsBtnActionPerformed(evt);
            }
        });
        add(monitorVitalSignsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 300, 53));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PDCNurseWorkAreaJPanel pdcnwjp = (PDCNurseWorkAreaJPanel) component;
        pdcnwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void sendToDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToDoctorBtnActionPerformed
        PDCPrimaryDoctorOrganization pdcPDOrg = null;
        PrimaryDoctor primaryDoctor = null;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof PDCPrimaryDoctorOrganization) {
                pdcPDOrg = (PDCPrimaryDoctorOrganization) org;
                for (Employee emp : pdcPDOrg.getEmployeeDirectory().getEmployeeList()) {
                    if (emp instanceof PrimaryDoctor) {
                        primaryDoctor = (PrimaryDoctor) emp;
                    }
                }
            }
        }
        if (primaryDoctor != null) {
            RequestPDCNursePDCPrimaryDoctor request7 = new RequestPDCNursePDCPrimaryDoctor();
            request7.setMessage("Patient Send to Doctor with vital signs and feedback from nurse");
            request7.setPatient(request6.getPatient());
            request7.setSender(userAccount);
            request7.setReceiver(primaryDoctor.getUserAccount());
            request7.setStatus("Sent To Doctor");
            request6.setStatus("Sent To Doctor");
            WorkRequest lastRequest = null;
            for (WorkRequest request5: request6.getPatient().getUserAccount().getWorkQueue().getWorkRequestList()){
                if (request5 instanceof RequestPatientPDCReceptionist){
                    lastRequest = request5;
                }
            }
            if(lastRequest!= null){
                lastRequest.setStatus("Send To Doctor");
            }
            userAccount.getWorkQueue().getWorkRequestList().add(request7);
            primaryDoctor.getUserAccount().getWorkQueue().getWorkRequestList().add(request7);
            JOptionPane.showMessageDialog(null, "Patient is Sent to Doctor");
            
        }


    }//GEN-LAST:event_sendToDoctorBtnActionPerformed

    private void monitorVitalSignsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorVitalSignsBtnActionPerformed
        // TODO add your handling code here:
        Methods.inputVitalSigns(request6.getPatient());
        JOptionPane.showMessageDialog(null, "Vital Signs monitored! Send Patient To Doctor");
    }//GEN-LAST:event_monitorVitalSignsBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton monitorVitalSignsBtn;
    private javax.swing.JButton sendToDoctorBtn;
    // End of variables declaration//GEN-END:variables

}
