/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PDCNurseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PDCNurseOrganization;
import UserInterface.PDCPrimaryDoctorRole.*;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RequestPDCReceptionistPDCNurse;
import Business.WorkQueue.RequestPatientPDCReceptionist;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohit
 */
public class PDCNurseWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PDCNurseOrganization pdcNurseOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;

    /**
     * Creates new form PDCPrimaryDoctorWorkAreaJPanel
     */
    public PDCNurseWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.pdcNurseOrganization = (PDCNurseOrganization) organization;
        this.enterprise = enterprise;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("PDC Nurse Work Area");

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Patient", "Message", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(processJButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJButton)
                    .addComponent(processJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }
        WorkRequest request6 = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if (request6.getStatus().equalsIgnoreCase("Sent To Doctor")) {
            JOptionPane.showMessageDialog(null, "Request already processed.");
            return;
        } else {
            request6.setReceiver(userAccount);
            request6.setStatus("Patient is being attended by Nurse");
            WorkRequest lastRequest = null;
            for (WorkRequest request5: request6.getPatient().getUserAccount().getWorkQueue().getWorkRequestList()){
                if (request5 instanceof RequestPatientPDCReceptionist){
                    lastRequest = request5;
                }
            }
            if(lastRequest!= null){
                lastRequest.setStatus("Patient is being attended by Nurse");
            }
            populateTable();
            JOptionPane.showMessageDialog(null, "Patient is being attended by nurse");
        }
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        RequestPDCReceptionistPDCNurse request6 = (RequestPDCReceptionistPDCNurse) workRequestJTable.getValueAt(selectedRow, 0);
        if (request6.getStatus().equalsIgnoreCase("Patient is being attended by Nurse") || request6.getStatus().equalsIgnoreCase("Being Monitored by Nurse")) {
            request6.setStatus("Being Monitored by Nurse");
            WorkRequest lastRequest = null;
            for (WorkRequest request5: request6.getPatient().getUserAccount().getWorkQueue().getWorkRequestList()){
                if (request5 instanceof RequestPatientPDCReceptionist){
                    lastRequest = request5;
                }
            }
            if(lastRequest!= null){
                lastRequest.setStatus("Being Monitored by Nurse");
            }
            PDCNurseProcessJPanel pdcNurseProcessJPanel = new PDCNurseProcessJPanel(userProcessContainer, request6, userAccount, enterprise);
            userProcessContainer.add("pdcNurseProcessjPanel", pdcNurseProcessJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else if (request6.getStatus().equalsIgnoreCase("Sent To Doctor")) {
            JOptionPane.showMessageDialog(null, "Already Sent To Doctor");
        } else {
            JOptionPane.showMessageDialog(null, "Please Assign yourself to the Patient First");
        }
    }//GEN-LAST:event_processJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request6 : pdcNurseOrganization.getWorkQueue().getWorkRequestList()) {
            
                Object[] row = new Object[5];
                row[0] = request6;

                row[1] = request6.getPatient();
                row[2] = request6.getMessage();
                row[3] = request6.getReceiver();
                row[4] = request6.getStatus();
                model.addRow(row);
            

        }
    }
}
