/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Employee.Patient;
import Business.Organization.PatientOrganization;
import Business.PatientAttributes.VitalSigns;
import Business.UserAccount.UserAccount;
import Business.Utils.MyIntegerVerifier;
import Business.Utils.MyStringVerifier;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mohit
 */
public class PatientAddVitalSignsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PatientOrganization patientOrganization;
    private PatientWorkAreaJPanel pwajp;
    private Patient patient;

    /**
     * Creates new form PatientAddVitalSignsJPanel
     */
    public PatientAddVitalSignsJPanel(JPanel userProcessContainer, PatientOrganization patientOrganization, PatientWorkAreaJPanel pwajp, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patientOrganization = patientOrganization;
        this.pwajp = pwajp;
        this.patient = patient;
        patientNameTxtField.setText(patient.getName());
        MyIntegerVerifier myIntegerVerifier = new MyIntegerVerifier();
        heartRateTxtField.setInputVerifier(myIntegerVerifier);
        respiratoryRateTxtField.setInputVerifier(myIntegerVerifier);
        bloodPressureTxtField.setInputVerifier(myIntegerVerifier);
        weightInKgTxtField.setInputVerifier(myIntegerVerifier);
        ecgTxtField.setInputVerifier(myIntegerVerifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addVitalSignsBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        heartRateTxtField = new javax.swing.JTextField();
        bloodPressureTxtField = new javax.swing.JTextField();
        respiratoryRateTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        patientNameTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        weightInKgTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ecgTxtField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Heart Rate");

        jLabel2.setText("Blood Pressure");

        addVitalSignsBtn.setText("Add Vital Signs");
        addVitalSignsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalSignsBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Respiratory Rate");

        jLabel4.setText("Patient Name");

        patientNameTxtField.setEditable(false);
        patientNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Weight in KG");

        jLabel6.setText("ECG");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(weightInKgTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bloodPressureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(respiratoryRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ecgTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(backBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(patientNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(addVitalSignsBtn)))))
                .addGap(354, 354, 354))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(patientNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bloodPressureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(respiratoryRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(weightInKgTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ecgTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVitalSignsBtn)
                    .addComponent(backBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameTxtFieldActionPerformed

    private void addVitalSignsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalSignsBtnActionPerformed
        // TODO add your handling code here:
        if(heartRateTxtField.getText().trim().length()==0 || respiratoryRateTxtField.getText().trim().length()==0 || weightInKgTxtField.getText().trim().length()==0 || ecgTxtField.getText().trim().length()==0 || bloodPressureTxtField.getText().trim().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Please enter all Values","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        VitalSigns vitalSigns = patient.getVitalSignsHistory().addVitalSigns();
        vitalSigns.setRespiratoryRate(Integer.parseInt(respiratoryRateTxtField.getText()));
        vitalSigns.setHeartRate(Integer.parseInt(heartRateTxtField.getText()));
        vitalSigns.setSystolicBloodPressure(Integer.parseInt(bloodPressureTxtField.getText()));
        vitalSigns.setWeightInKg(Integer.parseInt(weightInKgTxtField.getText()));
        vitalSigns.setEcg(Integer.parseInt(ecgTxtField.getText()));
        vitalSigns.setTimeStamp(new Date());

        vitalSigns.setStatus(vitalSignsStatusChecker());
        JOptionPane.showMessageDialog(this, "Vital Sign Recorded.", "Information", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_addVitalSignsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        pwajp.populateVitalSignsHistoryTable();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVitalSignsBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bloodPressureTxtField;
    private javax.swing.JTextField ecgTxtField;
    private javax.swing.JTextField heartRateTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField patientNameTxtField;
    private javax.swing.JTextField respiratoryRateTxtField;
    private javax.swing.JTextField weightInKgTxtField;
    // End of variables declaration//GEN-END:variables

    private boolean vitalSignsStatusChecker() {
        boolean status;
        int ecg = Integer.parseInt(ecgTxtField.getText());
        if (ecg <= 50) {
            status = false;
        } else {
            status = true;
        }

        return status;
    }
}
