/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ERGeneralDoctorTeamRole;

import Business.PatientAttributes.ERVisit;
import Business.PatientAttributes.VitalSigns;
import static Business.Utils.Methods.vitalSignsStatusChecker;
import Business.WorkQueue.RequestERCoordinatorERGeneral;
import Business.WorkQueue.RequestPatientAmbulance;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mohit
 */
public class ERGeneralDoctorProcessJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private RequestERCoordinatorERGeneral request4;
    private ERGeneralDoctorTeamWorkAreaJPanel ergdtwajp;

    /**
     * Creates new form ERGeneralDoctorProcessJPanel
     */
    public ERGeneralDoctorProcessJPanel(JPanel userProcessContainer, RequestERCoordinatorERGeneral request4, ERGeneralDoctorTeamWorkAreaJPanel ergdtwajp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request4 = request4;
        this.ergdtwajp = ergdtwajp;
        patientNameTxtField.setText(request4.getPatient().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        patientNameTxtField = new javax.swing.JTextField();
        operatePatientBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedBackTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        releasePatientBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Patient");

        patientNameTxtField.setEditable(false);
        patientNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameTxtFieldActionPerformed(evt);
            }
        });

        operatePatientBtn.setText("Revive Patient");
        operatePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatePatientBtnActionPerformed(evt);
            }
        });

        feedBackTextArea.setColumns(20);
        feedBackTextArea.setRows(5);
        jScrollPane1.setViewportView(feedBackTextArea);

        jLabel5.setText("Feedback");

        releasePatientBtn.setText("Release Patient");
        releasePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releasePatientBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(patientNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(operatePatientBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(releasePatientBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(377, 377, 377))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addComponent(operatePatientBtn)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backJButton)
                            .addComponent(releasePatientBtn))))
                .addGap(279, 279, 279))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        ergdtwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void operatePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatePatientBtnActionPerformed
        // TODO add your handling code here:
        //attribite im ervisit;
        //change status of request to patient operated
        request4.setStatus("Patient is being monitored and revived");
        WorkRequest lastRequest = null;
        for (WorkRequest request : request4.getPatient().getUserAccount().getWorkQueue().getWorkRequestList()) {
            if (request instanceof RequestPatientAmbulance) {
                lastRequest = request;
            }
        }
        if (lastRequest != null) {
            lastRequest.setStatus("Patient is being monitored and revived");
        }
        int size = request4.getPatient().getErVisitHistory().getErVisitHistory().size();
        ERVisit erVisit = request4.getPatient().getErVisitHistory().getErVisitHistory().get(size - 1);
        erVisit.setIsOperatedBygeneralTeam(true);
        erVisit.setOperatedBy(request4.getReceiver().getEmployee());
        JOptionPane.showMessageDialog(null, "Patient is being revived");
    }//GEN-LAST:event_operatePatientBtnActionPerformed

    private void releasePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releasePatientBtnActionPerformed
        // TODO add your handling code here:
        //change status if request to patient released
        if (feedBackTextArea.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Leave a Feedback");
            return;
        } else {
            request4.setStatus("Patient is operated and Released");
            WorkRequest lastRequest = null;
            for (WorkRequest request : request4.getPatient().getUserAccount().getWorkQueue().getWorkRequestList()) {
                if (request instanceof RequestPatientAmbulance) {
                    lastRequest = request;
                }
            }
            if (lastRequest != null) {
                lastRequest.setStatus("Patient is operated and Released");
            }
            int size = request4.getPatient().getErVisitHistory().getErVisitHistory().size();
            ERVisit erVisit = request4.getPatient().getErVisitHistory().getErVisitHistory().get(size - 1);
            erVisit.setERDoctorFeedback(feedBackTextArea.getText());
            JOptionPane.showMessageDialog(null, "Patient is Revived and Released");
            VitalSigns vitalSigns = request4.getPatient().getVitalSignsHistory().addVitalSigns();
            vitalSigns.setRespiratoryRate(20);
            vitalSigns.setHeartRate(72);
            vitalSigns.setSystolicBloodPressure(90);
            vitalSigns.setWeightInKg(80);
            vitalSigns.setEcg(48);
            vitalSigns.setTimeStamp(new Date());
            vitalSigns.setStatus(vitalSignsStatusChecker(48));
        }
    }//GEN-LAST:event_releasePatientBtnActionPerformed

    private void patientNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextArea feedBackTextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton operatePatientBtn;
    private javax.swing.JTextField patientNameTxtField;
    private javax.swing.JButton releasePatientBtn;
    // End of variables declaration//GEN-END:variables
}
